-- INSERT INTO burgers (name) VALUES ("Do Brussel Burger");
-- INSERT INTO burgers (name) VALUES ("Burger a la Mode");
-- INSERT INTO burgers (name) VALUES ("Ruta-Bag-A Burger");
-- INSERT INTO burgers (name) VALUES ("The Cauliflower's Cumin From Inside the House Burger");
-- INSERT INTO burgers (name) VALUES ("Gourdon-Hamsey Burger Burger");
-- INSERT INTO burgers (name) VALUES ("Poutine on the Ritz Burger");